### ISSUE TITLE
Isolated worker SDK question

### ISSUE THREAD

**Issue by SeanFeldman** [fmichellonet/AzureFunctions.Extensions.OpenIDConnect#14]
Does it work with Isolated Worker SDK?
Thank you.

**Comment by fmichellonet** [comment]
Hello,

Sorry, i've never has to work with Isolated Worker. 
Are you facing an issue ?

**Comment by SeanFeldman** [comment]
I haven't tried it out yet, just was wondering if you've had a chance to validate it against the Isolated Worker (Out of Process) SDK.
I'll give it a try and update the issue.

**Comment by SeanFeldman** [comment]
I've tried a basic HTTP triggered function with Isolated worker SDK and `[Authorize]` didn't prevent an anonymous request.

Program.cs

```c#
using AzureFunctions.Extensions.OpenIDConnect.Configuration;
using Microsoft.Extensions.Hosting;

var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults()
    .ConfigureServices((builder, services) =>
    {
        var audience = Environment.GetEnvironmentVariable("OpenIdConnect_Audience");
        var issuer = Environment.GetEnvironmentVariable("OpenIdConnect_Issuer");
        var issuerUrl = Environment.GetEnvironmentVariable("OpenIdConnect_IssuerUrl");
        services.AddOpenIDConnect(config =>
        {
            config.SetTokenValidation(TokenValidationParametersHelpers.Default(audience, issuer));
            config.SetIssuerBaseUrlConfiguration(issuerUrl);
        });
    })
    .Build();

host.Run();
```

Function:

```c#
using System.Net;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.Extensions.Logging;

namespace TestFunction;

[Authorize]
public class Function1
{
    private readonly ILogger _logger;

    public Function1(ILoggerFactory loggerFactory)
    {
        _logger = loggerFactory.CreateLogger<Function1>();
    }

    // [Authorize]
    [Function("Function1")]
    public HttpResponseData Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req)
    {
        _logger.LogInformation("C# HTTP trigger function processed a request.");

        var response = req.CreateResponse(HttpStatusCode.OK);
        response.Headers.Add("Content-Type", "text/plain; charset=utf-8");

        response.WriteString("Welcome to Azure Functions!");

        return response;
    }
}
```

**Comment by fmichellonet** [comment]
Thanks for your reports, i'll try to have a look to this issue in the next few days....

**Comment by fmichellonet** [comment]
I'm really sorry @SeanFeldman but I didn't had time to have a look to this issue. And now I'm in holiday with family etc... Without access to a comp.
Anyway, to solve this issue I would try to register the authentication Middleware and configure it

```
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
.AddJwtBearer(JwtBearerDefaults.AuthenticationScheme,
        options => builder.Configuration.Bind("JwtSettings", options))

```
And call `UseAuthentication`. More information here : https://docs.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-6.0
Once done, the authorize attribute (without role) should work.

**Comment by SeanFeldman** [comment]
No need to apologize. It's summertime. I've likely broken a few promises myself when it comes to issues/PRs 🙂
I'll give it a try. Thank you for the pointer.

**Comment by fmichellonet** [comment]
@SeanFeldman , @SORencber just a quick update to let you know I'm working on a mn authentication  middleware for isolated worker use case.
Might be ready by the end of the weekend

**Comment by SeanFeldman** [comment]
@fmichellonet that's great. BTw, don't know if you've seen https://github.com/Azure/azure-functions-dotnet-worker/issues/856. Functions team is committed to bringing Authentication and Authorization to the Isolated Worker SDK.

**Comment by fmichellonet** [comment]
@SeanFeldman, thanks for the links, i had missed that news.
I think i'll release a middleware till the official one come out.

**Comment by fmichellonet** [comment]
version 0.9.0 introduces isolated worker support. I close this issue.
