### ISSUE TITLE
The isolated worker has the concept of the middleware. The execution model is very different from the InProc SDK.

### ISSUE THREAD

**Issue by SORencber** [fmichellonet/AzureFunctions.Extensions.OpenIDConnect#17]
Could you find any Solution ? 
If you can  any Solution find, Could you write to me . 

thanks. 

The isolated worker has the concept of the middleware. The execution model is very different from the InProc SDK.
Perhaps, the context provided in the middleware could be leveraged to perform the authorization. Authentication using middleware is straightforward.

_Originally posted by @SeanFeldman in https://github.com/fmichellonet/AzureFunctions.Extensions.OpenIDConnect/issues/14#issuecomment-1157880577_

**Comment by SeanFeldman** [comment]
@SORencber, I don't quite understand the need to raise a duplicate issue for the already existing one you've referenced yourself.
If #14 remains open, it indicates there's no solution yet. Therefore, I suggest you close this one and subscribe/follow #14.

**Comment by fmichellonet** [comment]
@SORencber thanks for your interest in this lib. 
As @SeanFeldman stated this is a duplicate. Please follow the other issue.
